### ISSUE TITLE
Versions after 1.21 are slower to navigate between folders

### ISSUE THREAD

**Issue by MrPotatoZed** [manuel-hegner/foundry-filepicker-favorites#51] opened 2022-06-06 22:46 UTC
I wouldn't call this a bug but just wanted to make sure you were aware that versions after 1.21 seem to slow down the use of the filepicker to a noticeable degree. 1.24 may be slightly faster than 1.23 but I haven't tested this to be sure and I might be imagining things. However, while 1.21 seems to move between folders at about the same speed as the core filepicker newer versions seem to take a second or two before moving to the selected folder. This is tested on the forge only, v 9.269, 5e 1.6.2. I get the same behavior in chrome and firefox. I don't see any errors in console. Videos showing what I'm talking about are below.
Version 1.24
![improvements1](https://user-images.githubusercontent.com/85974617/172260437-e3e5fb9d-c0fb-47b6-a829-1b75183f58a4.gif)
Version 1.21
![improvements3](https://user-images.githubusercontent.com/85974617/172260469-e15d0d9e-9628-4b15-a742-4264035f6e5c.gif) 
Nothing about this is game breaking and 1.21 is still working great but just wanted to give a heads up. Thank you for your work on this very helpful mod.

**Comment by manuel-hegner** [comment] 2022-06-07 11:57
Interesting. I have not thought of that. I assume the problem is that the newer version check for each "favorite button" if the user is actually able to access it. This of course takes as much time as the traversal itself for each button.

**Comment by manuel-hegner** [comment] 2022-06-07 12:58
Could you check if this is fixed in 1.2.5?

**Comment by MrPotatoZed** [comment] 2022-06-07 15:52
Yup, that did it! Moving super smoothly again.

**Closed** 2022-06-07 16:33 UTC
